credentials:
  usernames:
    admin:
      email: admin@admin.com
      name: Admin
      password: $2b$12$nJZ8GFkDInhBkVHl96e3EecWfg7ChricSCC1iN.bb5fL8KdqDLSjC
cookie:
  expiry_days: 30
  key: trcyvgubhinjmkl
  name: selections_streamlit_cookie
preauthorized: null